config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  passwordless_for :users

  root 'home#index'
  resources :accounts, only: [:index]
  resources :synchronizations, only: [:create]
  resources :ynab_budgets do
    resources :ynab_accounts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  passwordless_with :email

  has_many :ynab_budgets
  has_many :ynab_accounts, through: :ynab_budgets
end

app/models/ynab_account.rb
# frozen_string_literal: true

class YnabAccount < ApplicationRecord
  belongs_to :ynab_budget
  delegate :user, to: :ynab_budget
end

app/models/ynab_budget.rb
class YnabBudget < ApplicationRecord
  belongs_to :user
  has_many :ynab_accounts
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  # To add force user to authenticate, uncomment bellow.
  # before_action :require_user!

  def index
    render json: YnabAccount.all, root: nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Passwordless::ControllerHelpers

  helper_method :current_user

  private

  def current_user
    @current_user ||= authenticate_by_session(User)
  end

  def require_user!
    return if current_user
    redirect_to root_path, flash: { error: 'You are not worthy!' }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/synchronizations_controller.rb
# frozen_string_literal: true

class SynchronizationsController < ApplicationController
  # To add force user to authenticate, uncomment bellow.
  # before_action :require_user!

  skip_before_action :verify_authenticity_token

  def create
    result = Ynab::CreateTransactions.new.call(transaction_data)
    if result.success?
      render json: result.transactions, root: nil
    else
      render json: { error: 'Failed' }, root: nil
    end
  end

  private

  def synchronzation_params
    params.require(:synchronization).permit(:ynab_account_id, :ynab_budget_id)
  end

  def ynab_budget
    @ynab_budget ||= YnabBudget.find(synchronzation_params[:ynab_budget_id])
  end

  def ynab_account
    @ynab_account ||= YnabAccount.find(synchronzation_params[:ynab_account_id])
  end

  def transaction_data
    {
      budget_external_id: ynab_budget.external_id,
      account_external_id: ynab_account.external_id,
      transactions: [
        {
          date: Date.today,
          payee_name: 'Another Test Payee',
          memo: 'I was also created through the API',
          cleared: 'Uncleared',
          approved: false,
          amount: 232
        },
        {
          date: Date.today,
          payee_name: 'Another Test Payee',
          memo: 'I was also created through the API',
          cleared: 'Uncleared',
          approved: false,
          amount: 343
        }
      ]
    }
  end
end

app/controllers/ynab_accounts_controller.rb
class YnabAccountsController < ApplicationController
  before_action :set_ynab_budget, only: [:index, :new]
  before_action :set_ynab_account, only: [:show, :edit, :update, :destroy]

  # GET /ynab_accounts
  # GET /ynab_accounts.json
  def index
    @ynab_accounts = @ynab_budget.ynab_accounts
  end

  # GET /ynab_accounts/1
  # GET /ynab_accounts/1.json
  def show
  end

  # GET /ynab_accounts/new
  def new
    @ynab_account = @ynab_budget.ynab_accounts.build
  end

  # GET /ynab_accounts/1/edit
  def edit
  end

  # POST /ynab_accounts
  # POST /ynab_accounts.json
  def create
    @ynab_account = YnabAccount.new(ynab_account_params)

    respond_to do |format|
      if @ynab_account.save
        format.html { redirect_to @ynab_account, notice: 'Ynab account was successfully created.' }
        format.json { render :show, status: :created, location: @ynab_account }
      else
        format.html { render :new }
        format.json { render json: @ynab_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ynab_accounts/1
  # PATCH/PUT /ynab_accounts/1.json
  def update
    respond_to do |format|
      if @ynab_account.update(ynab_account_params)
        format.html { redirect_to @ynab_account, notice: 'Ynab account was successfully updated.' }
        format.json { render :show, status: :ok, location: @ynab_account }
      else
        format.html { render :edit }
        format.json { render json: @ynab_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ynab_accounts/1
  # DELETE /ynab_accounts/1.json
  def destroy
    @ynab_account.destroy
    respond_to do |format|
      format.html { redirect_to ynab_accounts_url, notice: 'Ynab account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ynab_account
      @ynab_account = YnabAccount.where(ynab_budget_id: params[:ynab_budget_id]).find(params[:id])
    end

    def set_ynab_budget
      @ynab_budget = YnabBudget.find(params[:ynab_budget_id])
    end

    # Only allow a list of trusted parameters through.
    def ynab_account_params
      params.require(:ynab_account).permit(:name, :external_id, :account_type, :ynab_budget_id)
    end
end

app/controllers/ynab_budgets_controller.rb
class YnabBudgetsController < ApplicationController
  before_action :set_ynab_budget, only: [:show, :edit, :update, :destroy]

  # GET /ynab_budgets
  # GET /ynab_budgets.json
  def index
    @ynab_budgets = YnabBudget.all.includes(:user)
  end

  # GET /ynab_budgets/1
  # GET /ynab_budgets/1.json
  def show
  end

  # GET /ynab_budgets/new
  def new
    @ynab_budget = YnabBudget.new
  end

  # GET /ynab_budgets/1/edit
  def edit
  end

  # POST /ynab_budgets
  # POST /ynab_budgets.json
  def create
    @ynab_budget = YnabBudget.new(ynab_budget_params)

    respond_to do |format|
      if @ynab_budget.save
        format.html { redirect_to @ynab_budget, notice: 'Ynab budget was successfully created.' }
        format.json { render :show, status: :created, location: @ynab_budget }
      else
        format.html { render :new }
        format.json { render json: @ynab_budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ynab_budgets/1
  # PATCH/PUT /ynab_budgets/1.json
  def update
    respond_to do |format|
      if @ynab_budget.update(ynab_budget_params)
        format.html { redirect_to @ynab_budget, notice: 'Ynab budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @ynab_budget }
      else
        format.html { render :edit }
        format.json { render json: @ynab_budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ynab_budgets/1
  # DELETE /ynab_budgets/1.json
  def destroy
    @ynab_budget.destroy
    respond_to do |format|
      format.html { redirect_to ynab_budgets_url, notice: 'Ynab budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ynab_budget
      @ynab_budget = YnabBudget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ynab_budget_params
      params.require(:ynab_budget).permit(:name, :external_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ynab_accounts_helper.rb
module YnabAccountsHelper
end

app/helpers/ynab_budgets_helper.rb
module YnabBudgetsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Home</h1>
      <a class="btn btn-primary" href="<%= users.sign_in_path %>">Sign in</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinkYnab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="c-app">
    <div class="c-wrapper">
      <header class="c-header">
        <!-- Header content here -->
        <%= render partial: "shared/header" %>
      </header>
      <div class="c-body">
        <main class="c-main">
          <%= yield %>
        </main>
      </div>
      <footer class="c-footer">
        <!-- Footer content here -->
        <span>Checkout code and contribute at <a href="https://github.com/fmfdias/tink-ynab">Tink YNAB Github</a>. Template: <a href="https://coreui.io">coreui</a></span>
      </footer>
    </div>
  </body>
  <body>
</html>

app/views/shared/_header.html.erb
<header class="c-header c-header-light px-3">
  <a class="c-header-brand" href="#">
    Tink YNAB Sync
  </a>
  <ul class="c-header-nav mr-auto">
    <li class="c-header-nav-item">
      <%= link_to(ynab_budgets_path, class: "c-header-nav-link") do %>
        YNAB Budgets
      <% end %>
    </li>
  </ul>
</header>

app/views/shared/_ynab_accounts_list.html.erb
<% display_ynab_budget = true if local_assigns[:display_ynab_budget].nil? %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">External ID</th>
      <th scope="col">Account Type</th>
      <% if display_ynab_budget %>
        <th scope="col">Budget</th>
      <% end %>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% ynab_accounts.each do |ynab_account| %>
    <tr>
      <th scope="row"><%= ynab_account.name %></th>
      <td><%= ynab_account.external_id %></td>
      <td><%= ynab_account.account_type %></td>
      <% if display_ynab_budget %>
        <td><%= link_to ynab_account.ynab_budget.name, ynab_account.ynab_budget %></td>
      <% end %>
      <td>
        <%= link_to [ynab_account.ynab_budget, ynab_account] do %>
          <i class="cil-notes"></i>
        <% end %>
      </td>
      <td>
        <%= link_to edit_ynab_budget_ynab_account_path(ynab_account.ynab_budget, ynab_account) do %>
          <i class="cil-pencil"></i>
        <% end %>
      </td>
      <td>
        <%= link_to [ynab_account.ynab_budget, ynab_account], method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="cil-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/ynab_accounts/_form.html.erb
<%= form_with(model: [ynab_account.ynab_budget, ynab_account], local: true) do |form| %>
  <% if ynab_account.errors.any? %>
    <div class="row">
      <div class="col" id="error_explanation">
        <h3><%= pluralize(ynab_account.errors.count, "error") %> prohibited this ynab_account from being saved:</h3>

        <ul>
          <% ynab_account.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form.label :external_id %>
      <%= form.text_field :external_id, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form.label :account_type %>
      <%= form.text_field :account_type, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form.label :budget %>
      <%= form.select :ynab_budget_id,
              YnabBudget.all.collect { |p| [ p.name, p.id ] },
              { include_blank: false },
              { class: "form-control" } %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col actions">
      <%= form.submit nil, data: { disable_with: false }, type: "submit", class: 'btn btn-primary' %>
      <%= link_to 'Back', ynab_budget_ynab_accounts_path(ynab_account.ynab_budget), type: "button", class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/ynab_accounts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Editing YNAB Account</h1>
    </div>
  </div>
  <%= render 'form', ynab_account: @ynab_account %>
</div>

app/views/ynab_accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h1><%= @ynab_budget.name %> - Accounts</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'shared/ynab_accounts_list', ynab_accounts: @ynab_accounts%>
    </div>
  </div>
</div>

app/views/ynab_accounts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New <% @ynab_budget.name %> Account</h1>
    </div>
  </div>
  <%= render 'form', ynab_account: @ynab_account %>
</div>

app/views/ynab_accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h1><%= @ynab_account.name %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>External:</strong>
      <%= @ynab_account.external_id %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Account type:</strong>
      <%= @ynab_account.account_type %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>Ynab budget:</strong>
      <%= link_to @ynab_account.ynab_budget.name, ynab_budget_path(@ynab_account.ynab_budget) %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Edit', edit_ynab_budget_ynab_account_path(@ynab_account.ynab_budget, @ynab_account), type: "button", class: 'btn btn-primary' %>
      <%= link_to 'Back', ynab_budget_ynab_accounts_path(@ynab_account.ynab_budget), type: "button", class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/ynab_budgets/_form.html.erb
<%= form_with(model: ynab_budget, local: true) do |form| %>
  <% if ynab_budget.errors.any? %>
    <div class="row">
      <div class="col" id="error_explanation">
        <h3><%= pluralize(ynab_budget.errors.count, "error") %> prohibited this ynab_budget from being saved:</h3>

        <ul>
          <% ynab_budget.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form.label :external_id %>
      <%= form.text_field :external_id, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= form.label :user_id %>
      <%= form.select :person_id,
              User.all.collect { |p| [ p.email, p.id ] },
              { include_blank: false },
              { class: "form-control" } %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col actions">
      <%= form.submit nil, data: { disable_with: false }, type: "submit", class: 'btn btn-primary' %>
      <%= link_to 'Back', ynab_budgets_path, type: "button", class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/ynab_budgets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Editing Ynab Budget</h1>
    </div>
  </div>
  <%= render 'form', ynab_budget: @ynab_budget %>
</div>

app/views/ynab_budgets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h1>Ynab Budgets</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">External ID</th>
            <th scope="col">User</th>
            <th scope="col" colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @ynab_budgets.each do |ynab_budget| %>
          <tr>
            <th scope="row"><%= ynab_budget.name %></th>
            <td><%= ynab_budget.external_id %></td>
            <td><%= ynab_budget.user.email %></td>
            <td>
              <%= link_to ynab_budget do %>
                <i class="cil-notes"></i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_ynab_budget_path(ynab_budget) do %>
                <i class="cil-pencil"></i>
              <% end %>
            </td>
            <td>
              <%= link_to ynab_budget, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="cil-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/ynab_budgets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New Ynab Budget</h1>
    </div>
  </div>
  <%= render 'form', ynab_budget: @ynab_budget %>
</div>

app/views/ynab_budgets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h1><%= @ynab_budget.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <strong>External:</strong>
      <%= @ynab_budget.external_id %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <strong>User:</strong>
      <%= @ynab_budget.user_id %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col">
      <h3>YNAB Accounts</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'shared/ynab_accounts_list', ynab_accounts: @ynab_budget.ynab_accounts, display_ynab_budget: false %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <%= link_to 'Edit', edit_ynab_budget_path(@ynab_budget), type: "button", class: 'btn btn-primary' %>
      <%= link_to 'Back', ynab_budgets_path, type: "button", class: 'btn btn-secondary' %>
    </div>
  </div>
</div>